name: Zowe CLI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zowe-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Zowe CLI
      run: npm install -g @zowe/cli@latest
    
    - name: Configure Zowe CLI
      env:
        ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
        ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
      run: |
        zowe profiles create zosmf-profile LearnCOBOL \
          --host 192.86.32.250 \
          --port 10443 \
          --user $ZOWE_USERNAME \
          --password $ZOWE_PASSWORD \
          --reject-unauthorized false
    
    - name: Run Zowe command
      run: zowe jobs list jobs --zosmf-profile LearnCOBOL
