name: Zowe CLI, USS Interaction, and File Upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zowe-uss-and-upload-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Zowe CLI
      run: npm install -g @zowe/cli@latest
    
    - name: Check and create directory if not exists
      env:
        ZOWE_OPT_HOST: 192.86.32.250
        ZOWE_OPT_PORT: 10443
        ZOWE_OPT_USER: ${{ secrets.ZOWE_USERNAME }}
        ZOWE_OPT_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        ZOWE_OPT_REJECT_UNAUTHORIZED: false
      run: |
        if ! zowe zos-files list uss-files "/z/${{ secrets.ZOWE_USERNAME }}/cobol-check" &>/dev/null; then
          echo "Directory does not exist. Creating it..."
          zowe zos-files create uss-dir "/z/${{ secrets.ZOWE_USERNAME }}/cobol-check"
        else
          echo "Directory already exists."
        fi

    - name: Upload cobol-check directory to USS
      env:
        ZOWE_OPT_HOST: 192.86.32.250
        ZOWE_OPT_PORT: 10443
        ZOWE_OPT_USER: ${{ secrets.ZOWE_USERNAME }}
        ZOWE_OPT_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        ZOWE_OPT_REJECT_UNAUTHORIZED: false
      run: |
        zowe zos-files upload dir-to-uss "./cobol-check" "/z/${{ secrets.ZOWE_USERNAME }}/cobol-check" --recursive --binary-files "cobol-check-0.2.9.jar"
    
    - name: Install sshpass
      run: sudo apt-get install sshpass
    
    - name: Connect to USS and verify upload
      env:
        ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
        ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
      run: |
        sshpass -p "$ZOWE_PASSWORD" ssh -o StrictHostKeyChecking=no $ZOWE_USERNAME@192.86.32.250 'ls -la /z/$ZOWE_USERNAME/cobol-check'
