name: Zowe CLI and USS Interaction

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zowe-and-uss-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Zowe CLI
      run: npm install -g @zowe/cli@latest
    
    - name: Install sshpass
      run: sudo apt-get install sshpass
    
    - name: Run Zowe command
      env:
        ZOWE_OPT_HOST: 192.86.32.250
        ZOWE_OPT_PORT: 10443
        ZOWE_OPT_USER: ${{ secrets.ZOWE_USERNAME }}
        ZOWE_OPT_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        ZOWE_OPT_REJECT_UNAUTHORIZED: false
      run: zowe jobs list jobs
    
    - name: Connect to USS and run commands
      env:
        ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
        ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
      run: |
        sshpass -p "$ZOWE_PASSWORD" ssh -o StrictHostKeyChecking=no $ZOWE_USERNAME@192.86.32.250 'pwd && ls -la'
