name: Zowe CLI Operations
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  zowe-operations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Zowe CLI
        run: npm install -g @zowe/cli@latest

      - name: Make scripts executable
        run: |
          chmod +x .github/scripts/zowe_operations.sh
          chmod +x .github/scripts/mainframe_operations.sh

      - name: Run Zowe operations
        env:
          ZOWE_OPT_HOST: 204.90.115.200
          ZOWE_OPT_PORT: 10443
          ZOWE_OPT_USER: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_OPT_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
          ZOWE_OPT_REJECT_UNAUTHORIZED: false
          ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
        run: .github/scripts/zowe_operations.sh

      - name: Perform mainframe operations
        env:
          ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        run: |
          sshpass -p "$ZOWE_PASSWORD" ssh -o StrictHostKeyChecking=no $ZOWE_USERNAME@204.90.115.200 'sh -s' < .github/scripts/mainframe_operations.sh
